### PR TITLE
Remove dependency from interface.ts

### LINKED ISSUE #150: Fix for a circular reference issue
Right now there's a circular reference path in our code base:

```
lib/interface.ts->
lib/apisession/session.ts->
lib/subscription/subscription.ts->
lib/util/historical-buffer-manager.ts->
lib/interface.ts
```

Will have to remove this circular reference problem.

### PR DESCRIPTION
**Pull request by ericlu88**
This PR changes the dependencies a bit so `interface.ts` becomes leaf node. It also tries to use interfaces as type definition rather than the concrete implementation. The following graph shows the dependencies after this change. This PR closes #150 .

test

### CODE REVIEW

**Comment by ericlu88** [comment]
`request` release 2.54.0 yesterday. However this change breaks `promisify` on request module as several people pointing out already @https://github.com/request/request/issues/1506. I've downgraded the dependency to `request` module back to 2.53.0.

**Comment by ericvw** [comment]
Let's back out the stuff to have `interface.ts` depend upon `blpapi-wrapper.ts`, so that when the API migrates into the `blpapi-node` project, there is less churn in the future.

**Comment by ericlu88** [comment]
@ericvw Agreed. I've undo some of the changes so that the `blpapi-wrapper.ts` is now at the leaf. This will ease the migration when that happens.

test

**Comment by ericlu88** [comment]
Rebase & pushed.

**Comment by ericvw** [comment]
lgtm

**Pull request merged**
