### PR TITLE
Add boolean option for controling whether to use CRL on server

### PR DESCRIPTION
**Pull request by ericlu88**
This changes add a boolean option `crlEnable` to control whether we want to use CRL on the server. The default option is `false`.

This is a follow-up changes for #108

### CODE REVIEW

**Comment by ericvw** [comment]
Could the boolean be implicit if the CRL file path is provided in the config?  It would reduce the config options to just one path.

**Comment by ericlu88** [comment]
I've changed the default value of `crl` config to be an empty string, and use that as a flag for not using `crl` on the server.

**Comment by yupinghu** [comment]
LGTM, will defer to @ericvw if he has other comments.

**Comment by ericvw** [comment]
Does `null` work instead of empty string?  It would be preferable; if it doesn't work, don't worry about it.

**Comment by ericlu88** [comment]
no I've tried it but `convict` complaint the default value is not a type of `String`

**Comment by ericvw** [comment]
Cool.  lgtm - please squash

**Comment by ericlu88** [comment]
Squashed.

**Pull request merged**
