### PR TITLE
Repository restructuring

### PR DESCRIPTION
**Pull request by ericvw**
This PR cleans up the `examples/` directory and creates the `test/` and `doc/` for appropriate content.

### CODE REVIEW

**Comment by ericlu88** [comment]
Maybe make sense to also move `cfg.json` out of example folder since it is an example server configuration file, while the others are client examples?

**Comment by ericvw** [comment]
I like that idea.  I am trying to determine where we could move it to or if it makes sense to make a subdirectory under `examples/` for this.

**Comment by ericlu88** [comment]
I am ok with `examples/config/`. Worst case, we will move it later again :)

**Comment by ericlu88** [comment]
@ericvw Any updates on this PR? Would like to merge this also before I rebase the subscription stuff.

**Comment by ericvw** [comment]
Rebased PR against latest `develop` branch with the `examples/config/` changes.

**Comment by ericlu88** [comment]
LGTM. @yupinghu Any comments?

**Comment by ericvw** [comment]
Rebased against `develop` again now that #7 is merged.

**Comment by yupinghu** [comment]
LGTM

**Pull request merged**
