### PR TITLE
Updated dependency on blpapi-node.

### LINKED ISSUE #79: blpapi-wrapper should return different error types
Currently, any time the wrapper returns an error, we reject with that error, which gets handled as a 500. We should allow the wrapper to return various error types and surface that to the client.

### PR DESCRIPTION
**Pull request by thmiceli**
Closes #79

### CODE REVIEW

**Comment by ericvw** [comment]
lgtm - awaiting on TravisCI to merge.

**Comment by thmiceli** [comment]
Looking at the CI failure...

**Comment by thmiceli** [comment]
I don't understand how my change could have made the test fail. I cannot reproduce the failure locally either (tried it with nodejs 0.10). It could be an intermittent failure unrelated with this change.

**Comment by ericvw** [comment]
TravisCI is happy now.  Going to go ahead with this and keep an eye out for the testing failures.

**Pull request merged**
